[build]
  command = "npm install -g babel-cli && npm audit fix && npm install && npm run build"
  node_version = "16.19.1"
  publish = "dist"

[dev]
  command = "npm start"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[build.environment]
  PORT = "3000"